services:

  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend

    ports:
      - "3000:3000"

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
      POSTGRES_DB: fleetdb

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    ports:
      - "6379:6379"
