services:

  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"
      - "5005:5005/udp"
    environment:
      DATABASE_URL: postgresql://fleet:fleet@postgres:5432/fleetdb

  frontend:
    build:
      context: ./frontend

    ports:
      - "3000:3000"

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
      POSTGRES_DB: fleetdb

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    ports:
      - "6379:6379"
