"""add status to telemetry

Revision ID: 6862f5737fdc
Revises: 4de6bc98d536
Create Date: 2026-07-10 14:47:05.061485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6862f5737fdc'
down_revision: Union[str, Sequence[str], None] = '4de6bc98d536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('status', sa.String(length=32), server_default='unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'status')
    # ### end Alembic commands ###
