"""Add battery

Revision ID: eddb86277b7b
Revises: a8da8fd557f4
Create Date: 2026-07-07 15:30:46.446768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddb86277b7b'
down_revision: Union[str, Sequence[str], None] = 'a8da8fd557f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first so existing rows don't violate NOT NULL
    op.add_column('telemetry', sa.Column('battery', sa.Float(), nullable=True))
    # Backfill existing rows with a sensible default (100.0 = full battery)
    op.execute("UPDATE telemetry SET battery = 100.0 WHERE battery IS NULL")
    # Now enforce NOT NULL constraint
    op.alter_column('telemetry', 'battery', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'battery')
    # ### end Alembic commands ###
